# use a compiler that allows us to pin to a libcxx that is compatible with
# https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/conda_build_config.yaml
# copied from cppyy-cling to maybe help the solver. (I don't remember why this might matter tbh.)
c_compiler_version:        # [osx]
  - 17                     # [osx]
cxx_compiler_version:      # [osx]
  - 17                     # [osx]
